// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyYdQO58DoZSiEnYRhGHeSD4bcNkF4vbc',
    appId: '1:1079152864593:web:173c3db246eae9cd2f3770',
    messagingSenderId: '1079152864593',
    projectId: 'todocould',
    authDomain: 'todocould.firebaseapp.com',
    storageBucket: 'todocould.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRlVuY1oRKZz4hcvLBrDuwyZgtmiX2Po',
    appId: '1:1079152864593:android:8ad7d4d259e256922f3770',
    messagingSenderId: '1079152864593',
    projectId: 'todocould',
    storageBucket: 'todocould.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWFheDKNPZywU9h689bRdfpwcyL6D4_Qo',
    appId: '1:1079152864593:ios:2ff19a08cae640222f3770',
    messagingSenderId: '1079152864593',
    projectId: 'todocould',
    storageBucket: 'todocould.appspot.com',
    iosBundleId: 'com.example.demoApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWFheDKNPZywU9h689bRdfpwcyL6D4_Qo',
    appId: '1:1079152864593:ios:2ff19a08cae640222f3770',
    messagingSenderId: '1079152864593',
    projectId: 'todocould',
    storageBucket: 'todocould.appspot.com',
    iosBundleId: 'com.example.demoApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyYdQO58DoZSiEnYRhGHeSD4bcNkF4vbc',
    appId: '1:1079152864593:web:b1e3c736475d4fbd2f3770',
    messagingSenderId: '1079152864593',
    projectId: 'todocould',
    authDomain: 'todocould.firebaseapp.com',
    storageBucket: 'todocould.appspot.com',
  );

}